baseURL = "https://blog.manabisystem.com/"
languageCode = "ja"
title = "まなんだブログ"
theme = "ananke"

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-165312579-1"

[taxonomies]
category = "categories"
tag = "tags"

[params]
  favicon = ""
  site_logo = ""
  description = "日々学んだことを記録しているブログです。"
  facebook = ""
  twitter = "https://twitter.com/manabisystem"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gray"
  featured_image = "images/owl.jpg"
  recent_posts_number = 5
  custom_css = ["/css/custom.css"]
